### PR TITLE
Adding test functions

### PR DESCRIPTION
**Pull request by ColwynGulliford**
This file PR brings in functions for loading 3D CST data into a FieldMesh object as well as helper functions for checking that associated fields in the FieldMesh object satisfy Maxwell's equations.

This functionality was tested on 3 examples: 3D field map data from CST for the Cornell DC gun, 3D data for a 975 MHz kicker cavity from CERN, 3D field data for the Fermilab 7 cell accelerating cavity.

In addition, the helper functions were tested with the Cornell injector solenoid 2D map and a 2D 7 Cell Cornell MLC cavity map.

### CODE REVIEW

**Comment by ChristopherMayes** [comment]
The functions need docstrings

**Comment by ColwynGulliford** [comment]
> The functions need docstrings

Added!

**Comment by ColwynGulliford** [comment]
> Remove the unchanged notebooks

Done.

**Comment by ChristopherMayes** [comment]
`[pmd_beamphysics/fields/analysis.py:726](http://localhost:8888/lab/tree/docs/examples/fields/pmd_beamphysics/fields/analysis.py#line=725): SyntaxWarning: invalid escape sequence '\D'
  ax2.set_ylabel("$\Delta$ " + units)`

**Pull request merged**
